# Generated by Django 5.2.13 on 2026-05-11 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("mobile", models.CharField(max_length=20)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("Goods", "Goods"), ("Service", "Service")],
                        max_length=50,
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=50, null=True)),
                ("hsn", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Referrer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=20)),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=20)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Franchisee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ledger_name", models.CharField(max_length=255)),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("pan", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_msme", models.BooleanField(default=False)),
                ("is_composition_scheme", models.BooleanField(default=False)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("address1", models.CharField(blank=True, max_length=255, null=True)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(default="India", max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.CharField(blank=True, max_length=50, null=True)),
                ("longitude", models.CharField(blank=True, max_length=50, null=True)),
                ("same_as_billing", models.BooleanField(default=True)),
                (
                    "shipping_ref_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_gstin",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "shipping_address1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_address2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "shipping_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "shipping_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("shipping_country", models.CharField(default="India", max_length=100)),
                (
                    "shipping_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_latitude",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shipping_longitude",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=20, null=True)),
                ("swift_code", models.CharField(blank=True, max_length=20, null=True)),
                ("correspondent_bank", models.TextField(blank=True, null=True)),
                ("dealer_code", models.CharField(blank=True, max_length=50, null=True)),
                ("assign_under_branch", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
