# Generated by Django 5.2.13 on 2026-05-21 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("estimate_no", models.CharField(max_length=50, unique=True)),
                ("estimate_type", models.CharField(default="Estimates", max_length=50)),
                ("estimate_date", models.DateField()),
                ("valid_till", models.DateField()),
                (
                    "reference_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_order_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("buyer_order_date", models.DateField(blank=True, null=True)),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sub_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "freight",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "packing",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "insurance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tcs",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("terms", models.TextField(blank=True, null=True)),
                ("bank", models.CharField(blank=True, max_length=100, null=True)),
                ("sales_rep", models.CharField(blank=True, max_length=100, null=True)),
                ("project", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_quotes",
                        to="core.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PremiumQuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                ("hsn", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "qty",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("unit", models.CharField(default="PCS", max_length=50)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("discount_type", models.CharField(default="%", max_length=10)),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "mrp",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.premiumquote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
