# Generated by Django 5.2.13 on 2026-05-31 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_premiumquote_premiumquoteitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module_name", models.CharField(max_length=255)),
                ("module_code", models.CharField(max_length=100, unique=True)),
                (
                    "menu_type",
                    models.CharField(
                        choices=[("menu", "menu"), ("submenu", "submenu")],
                        max_length=20,
                    ),
                ),
                ("route_path", models.CharField(blank=True, max_length=255, null=True)),
                ("icon_name", models.CharField(blank=True, max_length=100, null=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submodules",
                        to="core.module",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
