# Generated by Django 5.2.13 on 2026-05-31 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module", models.CharField(max_length=100)),
                ("series_name", models.CharField(max_length=100)),
                (
                    "mode",
                    models.CharField(
                        choices=[("Auto", "Auto"), ("Manual", "Manual")],
                        default="Auto",
                        max_length=20,
                    ),
                ),
                ("prefix", models.CharField(blank=True, max_length=50, null=True)),
                ("next_number", models.IntegerField(default=1)),
                ("suffix", models.CharField(blank=True, max_length=50, null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "financial_year",
                    models.CharField(default="2026-2027", max_length=20),
                ),
                ("cid", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
