# Generated by Django 5.2.13 on 2026-05-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_documentsequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("field_type", models.CharField(max_length=50)),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_item_grid", models.BooleanField(default=False)),
                ("include_total", models.BooleanField(default=False)),
                ("is_required", models.BooleanField(default=False)),
                ("display_in_print", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("subtypes", models.TextField(default='["All"]')),
                ("cid", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
