# Generated by Django 5.2.13 on 2026-06-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customfield"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="branch",
            table="tbl_branch",
        ),
        migrations.AlterModelTable(
            name="customer",
            table="tbl_customer",
        ),
        migrations.AlterModelTable(
            name="customfield",
            table="tbl_customfield",
        ),
        migrations.AlterModelTable(
            name="documentsequence",
            table="tbl_documentsequence",
        ),
        migrations.AlterModelTable(
            name="franchisee",
            table="tbl_franchisee",
        ),
        migrations.AlterModelTable(
            name="item",
            table="tbl_item",
        ),
        migrations.AlterModelTable(
            name="module",
            table="tbl_module",
        ),
        migrations.AlterModelTable(
            name="premiumquote",
            table="tbl_premiumquote",
        ),
        migrations.AlterModelTable(
            name="premiumquoteitem",
            table="tbl_premiumquoteitem",
        ),
        migrations.AlterModelTable(
            name="referrer",
            table="tbl_referrer",
        ),
        migrations.AlterModelTable(
            name="supplier",
            table="tbl_supplier",
        ),
    ]
