# Generated by Django 5.2.13 on 2026-06-02 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_branch_table_alter_customer_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfield",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.module"
            ),
        ),
    ]
