# Generated by Django 5.2.13 on 2026-06-04 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_customfield_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_type", models.CharField(max_length=100)),
                ("sub_type", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("terms", models.TextField(blank=True, null=True)),
                ("email_cc", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email_subject",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email_content", models.TextField(blank=True, null=True)),
                ("sms_msg_id", models.CharField(blank=True, max_length=100, null=True)),
                ("sms_content", models.TextField(blank=True, null=True)),
                (
                    "whatsapp_msg_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("whatsapp_content", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "db_table": "ab_compcontent",
                "unique_together": {("branch", "document_type", "sub_type")},
            },
        ),
    ]
