# Generated by Django 5.2.13 on 2026-06-04 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_defaultcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cid", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sales_form_config",
                    models.TextField(
                        blank=True, help_text="Maps to salSettings", null=True
                    ),
                ),
                (
                    "sales_charges_config",
                    models.TextField(
                        blank=True, help_text="Maps to salChargesCode", null=True
                    ),
                ),
                (
                    "purchase_charges_config",
                    models.TextField(
                        blank=True, help_text="Maps to purChargesCode", null=True
                    ),
                ),
                (
                    "receipt_charges_config",
                    models.TextField(
                        blank=True, help_text="Maps to recpChargesCode", null=True
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "db_table": "ab_compsettings",
            },
        ),
    ]
