# Generated by Django 5.2.13 on 2026-06-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_generalsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmtpSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cid", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("E", "Email"), ("S", "SMS")],
                        default="E",
                        max_length=1,
                    ),
                ),
                ("settings", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "db_table": "ab_compsmtp",
            },
        ),
    ]
