# Generated by Django 5.2.13 on 2026-06-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_appuser_userrole_accessdevice_useractivitylog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="template_permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
