# Generated by Django 4.2.10 on 2026-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_module_template_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolepermission',
            name='extras',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
