# Generated by Django 5.2.13 on 2026-06-05 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_userrolepermission_extras"),
    ]

    operations = [

        migrations.AddField(
            model_name="branch",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),

        migrations.AddField(
            model_name="branch",
            name="gstin",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),

        migrations.AddField(
            model_name="branch",
            name="pan",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),

        migrations.AddField(
            model_name="branch",
            name="work_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name="BranchBankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=20, null=True)),
                ("swift_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_branch_bank",
            },
        ),
        migrations.CreateModel(
            name="BranchShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address1", models.CharField(blank=True, max_length=255, null=True)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_addresses",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_branch_shipping",
            },
        ),
        migrations.CreateModel(
            name="BranchTagAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag_name", models.CharField(max_length=100)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_accesses",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_branch_tags",
            },
        ),
    ]
