# Generated by Django 5.2.13 on 2026-06-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_branch_address1_branch_address2_branch_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_column="tagName", max_length=100)),
                (
                    "tag_type",
                    models.CharField(db_column="tagType", default="B", max_length=10),
                ),
            ],
            options={
                "db_table": "tags",
            },
        ),
    ]
