# Generated by Django 4.2.10 on 2026-06-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tag_branch_address1_branch_address2_branch_createddt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='createddt',
            field=models.DateTimeField(blank=True, db_column='createdDt', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, db_column='emailId', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(db_column='isActive', default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='mobile',
            field=models.CharField(blank=True, db_column='mobileNo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='updateddt',
            field=models.DateTimeField(blank=True, db_column='updatedDt', null=True),
        ),
    ]
