# Generated by Django 4.2.10 on 2026-06-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_branch_address1_branch_address2_branch_createddt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='ledger_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
