# Generated by Django 4.2.10 on 2026-06-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_branch_additional_info_branch_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='attachment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
