# Generated by Django 5.2.13 on 2026-06-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_branch_attachment_alter_branch_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="msme_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="msme_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
