# Generated by Django 5.2.13 on 2026-06-09 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_branch_msme_number_branch_msme_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Stock Location Name"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ledger_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("is_msme", models.BooleanField(default=False)),
                ("msme_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "msme_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("pan", models.CharField(blank=True, max_length=10, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("is_composition_scheme", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "attachments",
                    models.TextField(
                        blank=True,
                        help_text="JSON array of attached file paths/data",
                        null=True,
                    ),
                ),
                ("address1", models.CharField(blank=True, max_length=255, null=True)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(default="India", max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "map_coordinates",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=20, null=True)),
                ("swift_code", models.CharField(blank=True, max_length=20, null=True)),
                ("ad_code", models.CharField(blank=True, max_length=50, null=True)),
                ("correspondent_bank", models.TextField(blank=True, null=True)),
                (
                    "address_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address_warehouses",
                        to="core.branch",
                    ),
                ),
                (
                    "bank_branch_assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_warehouses",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_warehouse",
            },
        ),
    ]
