# Generated by Django 4.2.10 on 2026-06-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('Branch', 'Branch'), ('Warehouse', 'Warehouse'), ('Franchisee', 'Franchisee')], max_length=50)),
                ('entity_id', models.IntegerField()),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ad_code', models.CharField(blank=True, max_length=50, null=True)),
                ('correspondent_bank', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_entity_bank',
            },
        ),
        migrations.CreateModel(
            name='EntityShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('Branch', 'Branch'), ('Warehouse', 'Warehouse'), ('Franchisee', 'Franchisee')], max_length=50)),
                ('entity_id', models.IntegerField()),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_ref_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('map_coordinates', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_entity_shipping',
            },
        ),
        migrations.RemoveField(
            model_name='branchshippingaddress',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='ad_code',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='city',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='correspondent_bank',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='country',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='map_coordinates',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='state',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='swift_code',
        ),
        migrations.AlterModelTable(
            name='branch',
            table=None,
        ),
        migrations.DeleteModel(
            name='BranchBankDetail',
        ),
        migrations.DeleteModel(
            name='BranchShippingAddress',
        ),
        migrations.AddIndex(
            model_name='entityshippingaddress',
            index=models.Index(fields=['entity_type', 'entity_id'], name='tbl_entity__entity__d4d3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='entitybankdetail',
            index=models.Index(fields=['entity_type', 'entity_id'], name='tbl_entity__entity__58bf39_idx'),
        ),
    ]
