# Generated by Django 4.2.10 on 2026-06-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_entitybankdetail_entityshippingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='locations',
            field=models.JSONField(blank=True, default=list, help_text="Array of location codes like ['B-1', 'W-2']"),
        ),
    ]
