# Generated by Django 5.2.13 on 2026-06-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_appuser_locations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                ("descr", models.TextField(blank=True, null=True)),
                (
                    "convFactor",
                    models.DecimalField(
                        db_column="convFactor",
                        decimal_places=6,
                        default=1.0,
                        max_digits=18,
                    ),
                ),
                (
                    "companyId",
                    models.IntegerField(blank=True, db_column="companyId", null=True),
                ),
                (
                    "branchId",
                    models.IntegerField(blank=True, db_column="branchId", null=True),
                ),
                ("isActive", models.BooleanField(db_column="isActive", default=True)),
                (
                    "createdBy",
                    models.IntegerField(blank=True, db_column="createdBy", null=True),
                ),
                (
                    "createdDt",
                    models.DateTimeField(
                        auto_now_add=True, db_column="createdDt", null=True
                    ),
                ),
                (
                    "updatedDt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedDt", null=True
                    ),
                ),
                (
                    "updatedBy",
                    models.IntegerField(blank=True, db_column="updatedBy", null=True),
                ),
                (
                    "relatedUnits",
                    models.JSONField(
                        blank=True,
                        db_column="relatedUnits",
                        default=list,
                        help_text="Stores multiple related units and their conversion factors like [{'relatedUnitId': 2, 'convFactor': 10}]",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_units",
            },
        ),
    ]
