# Generated by Django 4.2.10 on 2026-06-11 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='isDefault',
            field=models.BooleanField(db_column='isDefault', default=False),
        ),
        migrations.CreateModel(
            name='FranchiseeTagAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_name', models.CharField(max_length=100)),
                ('franchisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_accesses', to='core.franchisee')),
            ],
            options={
                'db_table': 'tbl_franchisee_tags',
            },
        ),
        migrations.CreateModel(
            name='FranchiseeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='franchisee_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('franchisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.franchisee')),
            ],
            options={
                'db_table': 'tbl_franchisee_attachments',
            },
        ),
    ]
