# Generated by Django 5.2.13 on 2026-06-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_unit_isdefault_franchiseetagaccess_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="branch_attachments/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_branch_attachments",
            },
        ),
    ]
